# Generated by Django 4.2.7 on 2023-11-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cate',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(null=True, upload_to='category')),
            ],
        ),
    ]
