# Generated by Django 4.2.7 on 2023-11-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('Item', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Desc', models.TextField()),
                ('Img', models.ImageField(null=True, upload_to='Menu')),
            ],
        ),
    ]
