# Generated by Django 4.2.7 on 2023-11-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_items_delete_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Img',
            field=models.ImageField(null=True, upload_to='items'),
        ),
        migrations.AddField(
            model_name='items',
            name='is_home_delivery_available',
            field=models.BooleanField(default=False),
        ),
    ]
