# Generated by Django 4.2.7 on 2023-11-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_is_home_delivery_available_items_is_delivery_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('Imag', models.ImageField(null=True, upload_to='news')),
            ],
        ),
    ]
