# Generated by Django 4.2.7 on 2023-11-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
