# Generated by Django 4.2.7 on 2023-11-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_news_id_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='is_delivery_available',
            field=models.BooleanField(default=True),
        ),
    ]
